### ISSUE TITLE
repo requires package in deleted branch

### ISSUE THREAD

**Issue by illperipherals** [helium/lorawan-sniffer#15]
Cargo.lock and Cargo.toml refer to a branch that has been deleted:
```lorawan-encoding = { git = "https://github.com/helium/rust-lorawan.git", features = ["full"], branch = "lthiery/cflist-types"}```
Spoke w/ Louis, and he knows what's up here.

**Comment by lthiery** [comment]
Should be handled in b338901f14a6a3d2f49d52fa033a9a6625d2d893
